name: hoge

on:
  push:
    branches:
      - main

jobs:
  hoge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: 17
